### ISSUE TITLE
Make historical Draft registered-validation regression import-hermetic

### ISSUE THREAD

**Issue by aroviqen** [SecPal/.github#996]
## Goal

Make the regression introduced by #993 truthfully verify that historical-registry
reconstruction is independent of candidate Draft HEAD ancestry without requiring
unrelated protected-main-only Python modules merely to load the projected test
module.

## Classification

`POST_MERGE_CORRECTIVE_LEAF_OF_992`;
`PRE_ENROLLMENT_DRAFT_INTEGRATION`;
`REGISTERED_VALIDATION_HERMITICITY`;
`HISTORICAL_SOURCE_COMPATIBILITY`;
`TEST_PROJECTION_DEPENDENCY`;
`SECURITY_AND_INTEGRITY`.

This leaf is a genuine prerequisite for #764 / PR #773. It is test-projection
compatibility work, not evidence of a production runtime failure.

## Observed failure

PR #773 is diagnostic evidence only and must remain unchanged. In a fresh
pre-enrollment Draft attempt, the formerly failing target now succeeds:

```text
test_ready_integration_reconstructs_prior_policy_from_central_history
Ran 1 test — OK
```

Complete Registered Validation then fails while loading the registered actions
suite:

```text
ImportError: cannot import name 'qualified_remediation_successor_loss'
from 'scripts.secpal_pr_review'
```

The registered command is:

```text
python3 -m unittest tests/secpal-pr-review-actions-unit.py
```

## Dependency evidence and root cause

At protected main `cf44c33c2c7db13fe444572795f874b7a7efe62a`
(tree `76f26bb8e51ff6043f0637bc9e8775f504b6b7bc`), the actions test imports both
`lifecycle_publication` and `qualified_remediation_successor_loss` at module load.
The latter binding is used only by the later qualified-remediation-successor
test class. It is not used by
`test_ready_integration_reconstructs_prior_policy_from_central_history`.

The immutable PR #773 Draft head
`36b0a7fc62247d0f76c4e21b9271986f11376bfb`
(tree `cf8434d12360ef3962680cbeee14702b9aa58b3b`) contains
`lifecycle_publication.py` but predates
`qualified_remediation_successor_loss.py`. The #993 wrapper projects the current
actions test into a detached ancestry-separated candidate and executes the target
test there, while production modules remain candidate-owned. Its fixture used a
current tree and therefore did not model the protected-main-only module's absence.

Root-cause classification: **D — combination of A and B**.

- **A:** `qualified_remediation_successor_loss` is an unnecessarily broad
  top-level test import for a bounded later test class.
- **B:** the #993 meta-regression separates ancestry but does not model the
  historical candidate's production dependency closure.
- **Not C:** the maintained boundary is not intended to inject arbitrary current
  production modules into a historical candidate. Expanding it would weaken the
  candidate-tree authority model.

## Relationship to #992 / #993

#992 correctly removed accidental live-checkout ancestry dependence from the
historical-registry reconstruction test, and #993 delivered that accepted fix
without production changes. This separate corrective leaf makes the new #993
wrapper compatible with the real historical-candidate import boundary. It does
not reopen or invalidate #992.

## Acceptance criteria

- [ ] Add a fail-first synthetic or immutable historical-candidate regression
      where current main is not an ancestor, no integration commit exists, the
      accepted actions test is projected, and the protected-main-only qualified
      remediation module is absent.
- [ ] Prove the starting protected main fails at the exact module-import boundary.
- [ ] Remove the unrelated top-level dependency or isolate the regression with a
      narrower deterministic dependency closure; do not suppress arbitrary
      import failures or skip tests that genuinely own the dependency.
- [ ] Prove the actions module loads and the historical-registry reconstruction
      test executes and passes in that topology.
- [ ] Prove the #993 outer ancestry-independence regression passes while current
      main remains a non-ancestor and no two-parent integration commit exists.
- [ ] Prove normal current-main validation still executes every qualified-
      remediation-successor-loss test and the full actions suite.
- [ ] Audit every registered Python test module's top-level imports against the
      historical supported boundary and classify sibling patterns.
- [ ] Run all related lifecycle suites, the complete maintained 19-command
      registered graph in ordinary and historical-Draft topology, exact changed-
      file pre-commit, formatting, REUSE/SPDX, `git diff --check`, and full
      preflight.
- [ ] Preserve all pre-enrollment source, registry, authorization, topology,
      tree, digest, repository-identity, and fail-closed invariants.
- [ ] Change no production runtime, registry schema/version, integration evidence
      version, product/profile documentation, PR #773 branch, or #773 authority.

## Non-goals

- Reopening #992 or expanding #937.
- Mutating #764's content or existing parent #761.
- Copying protected-main production modules into PR #773.
- Reusing authorization `issue-764-pr-773-pre-enrollment-cf44c33` or issuing a
  replacement authorization in this delivery.
- Continuing #764 / PR #773 after this leaf merges.

## SIMPLIFY_BEFORE_EXTEND

`NEW_PERMANENT_CONCEPT: NO`

Prefer a narrowly scoped import plus a truthful regression fixture. Do not change
validation projection semantics unless new fail-first evidence proves that
contract defective.
